
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE EQUALS LEFT_PARENTHESIS LOG MINUS MULTIPLY NAME NUMBER PLUS RIGHT_PARENTHESIS VAR_DEFINEexpression : expression PLUS expressionexpression : expression MINUS expressionexpression : expression MULTIPLY expressionexpression : expression DIVIDE expressionexpression : LEFT_PARENTHESIS expression RIGHT_PARENTHESISexpression : NUMBERexpression : NAMEstatement : VAR_DEFINE NAME EQUALS expressionexpression : LOG expressionstatement : expression'
    
_lr_action_items = {'LEFT_PARENTHESIS':([0,2,5,6,7,8,9,],[2,2,2,2,2,2,2,]),'NUMBER':([0,2,5,6,7,8,9,],[3,3,3,3,3,3,3,]),'NAME':([0,2,5,6,7,8,9,],[4,4,4,4,4,4,4,]),'LOG':([0,2,5,6,7,8,9,],[5,5,5,5,5,5,5,]),'$end':([1,3,4,11,12,13,14,15,16,],[0,-6,-7,-9,-1,-2,-3,-4,-5,]),'PLUS':([1,3,4,10,11,12,13,14,15,16,],[6,-6,-7,6,6,6,6,6,6,-5,]),'MINUS':([1,3,4,10,11,12,13,14,15,16,],[7,-6,-7,7,7,7,7,7,7,-5,]),'MULTIPLY':([1,3,4,10,11,12,13,14,15,16,],[8,-6,-7,8,8,8,8,8,8,-5,]),'DIVIDE':([1,3,4,10,11,12,13,14,15,16,],[9,-6,-7,9,9,9,9,9,9,-5,]),'RIGHT_PARENTHESIS':([3,4,10,11,12,13,14,15,16,],[-6,-7,16,-9,-1,-2,-3,-4,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,5,6,7,8,9,],[1,10,11,12,13,14,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS expression','expression',3,'p_sum','parser.py',10),
  ('expression -> expression MINUS expression','expression',3,'p_subtract','parser.py',15),
  ('expression -> expression MULTIPLY expression','expression',3,'p_multiply','parser.py',20),
  ('expression -> expression DIVIDE expression','expression',3,'p_divide','parser.py',25),
  ('expression -> LEFT_PARENTHESIS expression RIGHT_PARENTHESIS','expression',3,'p_expression_group','parser.py',34),
  ('expression -> NUMBER','expression',1,'p_expression_number','parser.py',39),
  ('expression -> NAME','expression',1,'p_expression_name','parser.py',44),
  ('statement -> VAR_DEFINE NAME EQUALS expression','statement',4,'p_statement_var_define','parser.py',56),
  ('expression -> LOG expression','expression',2,'p_statement_log','parser.py',61),
  ('statement -> expression','statement',1,'p_statement_expression','parser.py',65),
]
